[package]
name = "getargv"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
readme = "README.md"
authors = ["CamJN <getargv@narzt.cam>"]
homepage = "https://getargv.narzt.cam/"
documentation = "https://docs.rs/getargv"
repository = "https://github.com/getargv/getargv-rust/"
description = "The first and only library to provide a correct interface to the KERN_PROCARGS2 sysctl."
categories = ["api-bindings", "os::macos-apis"]
keywords = ["argv", "arguments", "macOS", "KERN_PROCARGS2", "sysctl"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getargv-sys = "0.3.0"
libc = "0.2.137"
